// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package filesystem.proxies;

public class File extends filesystem.proxies.Node
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FileSystem.File";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Path("Path"),
		File_FileDocument("FileSystem.File_FileDocument"),
		Node_Node("FileSystem.Node_Node");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public File(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FileSystem.File"));
	}

	protected File(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileMendixObject)
	{
		super(context, fileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("FileSystem.File", fileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FileSystem.File");
	}

	/**
	 * @deprecated Use 'File.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static filesystem.proxies.File initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return filesystem.proxies.File.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static filesystem.proxies.File initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new filesystem.proxies.File(context, mendixObject);
	}

	public static filesystem.proxies.File load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return filesystem.proxies.File.initialize(context, mendixObject);
	}

	public static java.util.List<filesystem.proxies.File> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<filesystem.proxies.File> result = new java.util.ArrayList<filesystem.proxies.File>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FileSystem.File" + xpathConstraint))
			result.add(filesystem.proxies.File.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of File_FileDocument
	 */
	public final system.proxies.FileDocument getFile_FileDocument() throws com.mendix.core.CoreException
	{
		return getFile_FileDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of File_FileDocument
	 */
	public final system.proxies.FileDocument getFile_FileDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.File_FileDocument.toString());
		if (identifier != null)
			result = system.proxies.FileDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of File_FileDocument
	 * @param file_filedocument
	 */
	public final void setFile_FileDocument(system.proxies.FileDocument file_filedocument)
	{
		setFile_FileDocument(getContext(), file_filedocument);
	}

	/**
	 * Set value of File_FileDocument
	 * @param context
	 * @param file_filedocument
	 */
	public final void setFile_FileDocument(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.FileDocument file_filedocument)
	{
		if (file_filedocument == null)
			getMendixObject().setValue(context, MemberNames.File_FileDocument.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.File_FileDocument.toString(), file_filedocument.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final filesystem.proxies.File that = (filesystem.proxies.File) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FileSystem.File";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
